version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: dockerfile/Dockerfile.backend
        ports:
            - '5000:5000'
        volumes:
            - ./apps/backend:/app/apps/backend
        depends_on:
            - db
        environment:
            NODE_ENV: development

    frontend:
        build:
            context: .
            dockerfile: dockerfile/Dockerfile.frontend
        ports:
            - '3000:3000'
        volumes:
            - ./apps/frontend:/app/apps/frontend
        environment:
            NODE_ENV: development

    dashboard:
        build:
            context: .
            dockerfile: dockerfile/Dockerfile.dashboard
        ports:
            - '3001:3001'
        volumes:
            - ./apps/dashboard:/app/apps/dashboard
        environment:
            NODE_ENV: development

    db:
        image: postgres:15
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: quiz-inferno-owner
            POSTGRES_PASSWORD: rafeypostgres
            POSTGRES_DB: quiz-inferno
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
