FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/dashboard ./apps/dashboard

RUN pnpm install

RUN pnpm run build

EXPOSE 3001

CMD ["pnpm", "run", "start:dashboard"]

#docker build -t quiz-inferno-dashboard -f ./dockerfile/Dockerfile.dashboard .