FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN pnpm install

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:frontend"]


#docker build -t quiz-inferno-frontend -f ./dockerfile/Dockerfile.frontend .